#!/bin/bash
#                                    _        _          _ _ 
#                    _ __ ___   __ _| | _____| |__   ___| | |
#                   | '_ ` _ \ / _` | |/ / _ \ '_ \ / _ \ | |
#                   | | | | | | (_| |   <  __/ |_) |  __/ | |
#                   |_| |_| |_|\__,_|_|\_\___|_.__/ \___|_|_|
#                                                            
makebell() {
  #folder sounds are stored in
  c="/Users/shawn_gollatz/sb"
  #folder to count files in
  d="/Users/shawn_gollatz/Desktop/automator_ouput/originals"
  #counts all files including . and .. excluding ds_store
  e="$(ls -f "$d" | grep -v '.DS_Store' | wc -l)"
  #subtracts the . and .. from the count
  f=$( expr $e - 2 )
  #divides by four and stores the remainder in variable g
  g=$( expr $f % 4 )
  h=$( expr 4 - $g )
  echo "$c; $d'; $e $f $g $h"
  if [ $g == 0 ]; 
    then 
      say Operation Complete
      afplay -t 4 /Users/shawn_gollatz/sb/tr2.mp3
    else
      say "$h files to scan"
      afplay -t "$h" /Users/shawn_gollatz/sb/tr2.mp3
    fi 
}
makebell