#!/bin/bash
#
#                                      _             ____  
#                      _ __ ___   __ _| | _____     |___ \ 
#                     | '_ ` _ \ / _` | |/ / _ \_____ __) |
#                     | | | | | | (_| |   <  __/_____/ __/ 
#                     |_| |_| |_|\__,_|_|\_\___|    |_____|
#                                                                                                                       
#_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
#+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_
#
pinput="$*"
#
# Check for proper syntax

if [ -d "$pinput" ] 
then
    echo "Creating thumbs, contact sheets, .iso image and checksums...." 
else
    echo "Error.  Path provided "$pinput" does not point to a valid directory"
    echo "  Usage:  makeiso <path to directory>"
    echo "     ie:  makeiso \"/home/adam/Desktop/original-images-directory\""
    exit 1
fi

#_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
#+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_+_
# 
#
pmake2() {
  makecs "$pinput"
  makeiso "$pinput"
}
#
#
hash makecs >&/dev/null
if [ $? -eq 0 ]
then
  hash makeiso >&/dev/null
  if [ $? -eq 0 ]
  then
    pmake2
  else
    echo "makecs was detected but makeiso was not.  Exiting."
    break 2
  fi
else 
  echo "makecs not detected on your system.  Exiting."
  break
fi
#
#


