#!/bin/bash
blue() { echo -en '\033[36m'; }
red() { echo -en '\033[31m'; }
white() { echo -en '\033[00m'; }

me=$ME
dest=$HOMEPATH/.bash_aliases

newbashsh(){
if [ ! -f "$dest" ]; then
    touch "$dest"
    erck=$?
    if [ ! $erck -eq 0 ]; then
        echo "error $erck"
        exit $erck
    fi
fi

cnam=$(echo "alias $*" | awk -F\= '{ print $1 }')  
funn=$(echo "alias $*" | awk -F\= '{ print $2 }')  
. gcol yellow
glob=$(echo -E "$cnam"\=\'"$funn"\')
echo; echo "$glob"
. gcol white
echo -n "Press "; . gcol green; echo -n "(Y"; . gcol white; echo -n "|"; . gcol yellow; echo -n "n) "; . gcol white; echo -n "to accept the entry to "; . gcol navy; read -p "$dest: " yesno
. gcol white
    case $yesno in
            y*|Y*)
                    echo "$glob" >> "$dest"
                    erck=$?
                    if [ $erck -ne 0 ]; then 
                        echo "error $erck writing command"
                        exit $erck
                    fi
                    echo; echo "$glob"
                    echo -n "was created.  Type "
                    . gcol yellow
                    echo -n 'basha '
                    white
                    echo "to clone to root user, "
                    . gcol yellow
                    echo -n 'exec bash ' 
                    white
                    echo -n "and [ "
                    . gcol yellow
                    echo -n 'bashlist ' 
                    white
                    echo -n "| "
                    . gcol yellow
                    echo -n 'alias -p ' 
                    white
                    echo "] to view the new command"
                    ;;
            *)
                    echo "Aborting..."
                    exit 0
                    ;;
    esac
}

newbashsh $*
exit 0


#quickbashsh $*
#exit 0




